import { ColorId, MirrorId, MirrorPosition, StateColor } from '@/types/state8'

export const STATE_COLORS: Record<ColorId, StateColor> = {
  white: {
    id: 'white',
    name: 'WHITE',
    state: 'RELEASE',
    chinese: '白',
    actionChinese: '结束 / 清空 / 松手 / 重置',
    keywords: ['Release', 'Reset', 'Emptiness', 'Surrender'],
    question: 'What needs to be cleared before moving forward?',
    description: 'The state of complete clearance, ending what has completed its cycle, and creating space for renewal.',
    hex: '#f8fafc',
    glowHex: '#ffffff',
    rgb: '248, 250, 252',
    accentClass: 'text-slate-100',
    borderClass: 'border-slate-200/40',
    bgClass: 'bg-slate-100/10',
    glowClass: 'shadow-[0_0_25px_rgba(255,255,255,0.4)]',
  },
  purple: {
    id: 'purple',
    name: 'PURPLE',
    state: 'INSIGHT',
    chinese: '紫',
    actionChinese: '觉察 / 内观 / 直觉 / 看见',
    keywords: ['Insight', 'Awareness', 'Intuition', 'Clarity'],
    question: 'What do you already perceive beneath the surface?',
    description: 'The state of intuitive recognition, looking inward to observe the underlying pattern rather than reacting.',
    hex: '#c084fc',
    glowHex: '#a855f7',
    rgb: '192, 132, 252',
    accentClass: 'text-purple-300',
    borderClass: 'border-purple-500/40',
    bgClass: 'bg-purple-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(168,85,247,0.4)]',
  },
  blue: {
    id: 'blue',
    name: 'BLUE',
    state: 'VOICE',
    chinese: '蓝',
    actionChinese: '表达 / 信息 / 真相 / 沟通',
    keywords: ['Voice', 'Truth', 'Dialogue', 'Clarity'],
    question: 'What unsaid truth needs a clear voice?',
    description: 'The state of articulating honest reality, transparent exchange, and unfiltered objective transmission.',
    hex: '#60a5fa',
    glowHex: '#3b82f6',
    rgb: '96, 165, 250',
    accentClass: 'text-blue-300',
    borderClass: 'border-blue-500/40',
    bgClass: 'bg-blue-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(59,130,246,0.4)]',
  },
  pink: {
    id: 'pink',
    name: 'PINK',
    state: 'JOY',
    chinese: '粉',
    actionChinese: '感受 / 连接 / 接纳 / 愉悦',
    keywords: ['Joy', 'Connection', 'Warmth', 'Acceptance'],
    question: 'Where is genuine emotional resonance calling you?',
    description: 'The state of relational openness, unconditional acceptance, empathetic presence, and softened reception.',
    hex: '#f472b6',
    glowHex: '#ec4899',
    rgb: '244, 114, 182',
    accentClass: 'text-pink-300',
    borderClass: 'border-pink-500/40',
    bgClass: 'bg-pink-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(236,72,153,0.4)]',
  },
  green: {
    id: 'green',
    name: 'GREEN',
    state: 'SHIFT',
    chinese: '绿',
    actionChinese: '调整 / 成长 / 修正 / 转化',
    keywords: ['Shift', 'Growth', 'Realign', 'Adaptation'],
    question: 'What structural shift creates effortless expansion?',
    description: 'The state of flexible modification, organic transition, changing approach rather than forcing outcome.',
    hex: '#4ade80',
    glowHex: '#22c55e',
    rgb: '74, 222, 128',
    accentClass: 'text-emerald-300',
    borderClass: 'border-emerald-500/40',
    bgClass: 'bg-emerald-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(34,197,94,0.4)]',
  },
  yellow: {
    id: 'yellow',
    name: 'YELLOW',
    state: 'DISCERN',
    chinese: '黄',
    actionChinese: '判断 / 理性 / 规划 / 选择',
    keywords: ['Discern', 'Reason', 'Strategy', 'Choice'],
    question: 'What criteria separates essential from distraction?',
    description: 'The state of sharp evaluation, objective logic, systematic trade-offs, and grounded decision criteria.',
    hex: '#facc15',
    glowHex: '#eab308',
    rgb: '250, 204, 21',
    accentClass: 'text-yellow-300',
    borderClass: 'border-yellow-500/40',
    bgClass: 'bg-yellow-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(234,179,8,0.4)]',
  },
  orange: {
    id: 'orange',
    name: 'ORANGE',
    state: 'TIMING',
    chinese: '橙',
    actionChinese: '准备 / 时机 / 等待 / 酝酿',
    keywords: ['Timing', 'Patience', 'Incubation', 'Readiness'],
    question: 'Is the moment ripe, or is it building charge?',
    description: 'The state of cyclical alignment, respecting temporal maturity, preparing energy without premature premature release.',
    hex: '#fb923c',
    glowHex: '#f97316',
    rgb: '251, 146, 60',
    accentClass: 'text-orange-300',
    borderClass: 'border-orange-500/40',
    bgClass: 'bg-orange-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(249,115,22,0.4)]',
  },
  red: {
    id: 'red',
    name: 'RED',
    state: 'ACT',
    chinese: '红',
    actionChinese: '行动 / 执行 / 决断 / 突破',
    keywords: ['Act', 'Execute', 'Breakthrough', 'Resolve'],
    question: 'What already needs decisive action without delay?',
    description: 'The state of tangible manifestation, decisive physical momentum, and closing the gap between intent and execution.',
    hex: '#f87171',
    glowHex: '#ef4444',
    rgb: '248, 113, 113',
    accentClass: 'text-red-300',
    borderClass: 'border-red-500/40',
    bgClass: 'bg-red-500/10',
    glowClass: 'shadow-[0_0_25px_rgba(239,68,68,0.4)]',
  },
}

export const STATE_COLOR_LIST: StateColor[] = [
  STATE_COLORS.white,
  STATE_COLORS.purple,
  STATE_COLORS.blue,
  STATE_COLORS.pink,
  STATE_COLORS.green,
  STATE_COLORS.yellow,
  STATE_COLORS.orange,
  STATE_COLORS.red,
]

export const MIRROR_POSITIONS: Record<MirrorId, MirrorPosition> = {
  core: {
    id: 'core',
    index: 1,
    code: '01',
    name: 'CORE',
    chinese: '心',
    subtitle: '事情真正的核心',
    description: 'The root underlying pulse and true energetic center of this matter.',
    guidePrompt: 'What is at the very center of this inquiry?',
  },
  mind: {
    id: 'mind',
    index: 2,
    code: '02',
    name: 'MIND',
    chinese: '念',
    subtitle: '你如何理解这件事',
    description: 'Your conceptual lens, conscious assumptions, and mental framing.',
    guidePrompt: 'How your thoughts are structuring the situation.',
  },
  emotion: {
    id: 'emotion',
    index: 3,
    code: '03',
    name: 'EMOTION',
    chinese: '情',
    subtitle: '没有说出来的感受',
    description: 'Subconscious emotional tides, unspoken feelings, and somatic instinct.',
    guidePrompt: 'What feelings are operating beneath the conscious mind?',
  },
  action: {
    id: 'action',
    index: 4,
    code: '04',
    name: 'ACTION',
    chinese: '行',
    subtitle: '你目前正在做什么',
    description: 'Your current tangible momentum, physical posture, or lack of output.',
    guidePrompt: 'The pattern of current behavioral execution.',
  },
  relation: {
    id: 'relation',
    index: 5,
    code: '05',
    name: 'RELATION',
    chinese: '缘',
    subtitle: '谁或什么关系正在影响',
    description: 'Interpersonal fields, expectations, partner dynamics, and subtle attachments.',
    guidePrompt: 'The relational field mirroring back this situation.',
  },
  reality: {
    id: 'reality',
    index: 6,
    code: '06',
    name: 'REALITY',
    chinese: '境',
    subtitle: '外部现实条件',
    description: 'External constraints, objective resources, environmental friction or ground.',
    guidePrompt: 'The tangible facts on the ground right now.',
  },
  block: {
    id: 'block',
    index: 7,
    code: '07',
    name: 'BLOCK',
    chinese: '障',
    subtitle: '最大的盲点',
    description: 'The resistance point, hidden fixation, or friction draining momentum.',
    guidePrompt: 'Where the energy is trapped or overlooked.',
  },
  key: {
    id: 'key',
    index: 8,
    code: '08',
    name: 'KEY',
    chinese: '钥',
    subtitle: '下一步最需要的方向',
    description: 'The unlock principle, pivot vector, and recommended mode of navigation.',
    guidePrompt: 'The single state required to align the entire pattern.',
  },
}

export const MIRROR_POSITION_LIST: MirrorPosition[] = [
  MIRROR_POSITIONS.core,
  MIRROR_POSITIONS.mind,
  MIRROR_POSITIONS.emotion,
  MIRROR_POSITIONS.action,
  MIRROR_POSITIONS.relation,
  MIRROR_POSITIONS.reality,
  MIRROR_POSITIONS.block,
  MIRROR_POSITIONS.key,
]
