import { ColorId, StateColor } from './types'

export const STATE_COLORS: Record<ColorId, StateColor> = {
  white: {
    id: 'white',
    name: '白',
    state: '释放',
    keywords: ['清空', '结束', '松手', '重置'],
    question: '在继续向前之前，有什么需要先彻底清空与放下？',
    description: '一个周期已经自然走向终点。清空陈旧的执念与预期，给崭新的可能留出空白。',
    actionAdvice: '及时止损，归零重置，卸下负担。',
    hex: '#64748b',
    glowHex: '#cbd5e1',
    rgb: '100, 116, 139',
    lightBg: 'rgba(241, 245, 249, 0.85)',
    lightBorder: 'rgba(148, 163, 184, 0.35)',
    textColor: '#334155',
  },
  purple: {
    id: 'purple',
    name: '紫',
    state: '觉察',
    keywords: ['内观', '直觉', '看清', '顿悟'],
    question: '在表层情绪之下，你内心其实早就看清了什么？',
    description: '跳出局限，以内观的视角洞察底层模式。答案不在外界，而在你早已知晓的直觉里。',
    actionAdvice: '抽离旁观，信任直觉，看清规律。',
    hex: '#8b5cf6',
    glowHex: '#c4b5fd',
    rgb: '139, 92, 246',
    lightBg: 'rgba(245, 243, 255, 0.85)',
    lightBorder: 'rgba(196, 181, 253, 0.5)',
    textColor: '#6d28d9',
  },
  blue: {
    id: 'blue',
    name: '蓝',
    state: '表达',
    keywords: ['真相', '沟通', '信息', '清晰'],
    question: '有什么未曾明说的真实想法，急需被清晰表达？',
    description: '坦诚交流与客观对齐。用清晰精准的语言打破猜忌，直面客观事实。',
    actionAdvice: '不带情绪地说出真相，校准双方共识。',
    hex: '#3b82f6',
    glowHex: '#93c5fd',
    rgb: '59, 130, 246',
    lightBg: 'rgba(239, 246, 255, 0.85)',
    lightBorder: 'rgba(147, 197, 253, 0.5)',
    textColor: '#1d4ed8',
  },
  pink: {
    id: 'pink',
    name: '粉',
    state: '愉悦',
    keywords: ['感受', '连接', '接纳', '共鸣'],
    question: '你的心真正渴望什么样的温度与情感连接？',
    description: '放下坚硬的心理防备，允许情绪流动与温和接纳，从享受过程与人际共鸣中汲取力量。',
    actionAdvice: '柔化防备，善待自己，拥抱真实的感受。',
    hex: '#ec4899',
    glowHex: '#fbcfe8',
    rgb: '236, 72, 153',
    lightBg: 'rgba(253, 242, 248, 0.85)',
    lightBorder: 'rgba(249, 168, 212, 0.5)',
    textColor: '#be185d',
  },
  green: {
    id: 'green',
    name: '绿',
    state: '转化',
    keywords: ['调整', '成长', '变通', '修正'],
    question: '如果换一个结构或方法，这件事会怎样迎刃而解？',
    description: '不要用蛮力硬磕。通过灵活调整个体姿态与策略路径，实现顺势而为的有机生长。',
    actionAdvice: '换个切入点，调整节奏，顺势迭代。',
    hex: '#10b981',
    glowHex: '#a7f3d0',
    rgb: '16, 185, 129',
    lightBg: 'rgba(236, 253, 245, 0.85)',
    lightBorder: 'rgba(110, 231, 183, 0.5)',
    textColor: '#047857',
  },
  yellow: {
    id: 'yellow',
    name: '黄',
    state: '明辨',
    keywords: ['理性', '规划', '取舍', '判断'],
    question: '用清晰的客观标准来看，当务之急该保留什么、舍弃什么？',
    description: '用严谨的理性思维梳理混乱。建立明确的评估边界，做出不被干扰的精准抉择。',
    actionAdvice: '列出边界，分清主次，果断取舍。',
    hex: '#eab308',
    glowHex: '#fef08a',
    rgb: '234, 179, 8',
    lightBg: 'rgba(254, 252, 232, 0.85)',
    lightBorder: 'rgba(253, 224, 71, 0.5)',
    textColor: '#a16207',
  },
  orange: {
    id: 'orange',
    name: '橙',
    state: '时机',
    keywords: ['准备', '蓄力', '等待', '酝酿'],
    question: '此刻的时机成熟了吗？还是需要继续积攒势能？',
    description: '万物皆有时令。等待不是被动懈怠，而是保持敏锐、深度蓄能，静待最佳契机。',
    actionAdvice: '不急于出牌，持续蓄力，伺机而动。',
    hex: '#f97316',
    glowHex: '#fed7aa',
    rgb: '249, 115, 22',
    lightBg: 'rgba(255, 247, 237, 0.85)',
    lightBorder: 'rgba(253, 186, 116, 0.5)',
    textColor: '#c2410c',
  },
  red: {
    id: 'red',
    name: '红',
    state: '决断',
    keywords: ['行动', '执行', '突破', '魄力'],
    question: '哪一项关键行动必须立刻执行，绝不能再拖延？',
    description: '犹豫正在消耗你的动能。踏出不可逆的关键一步，用坚决的执行力打破所有猜测。',
    actionAdvice: '停止空想，果断出手，破局落地。',
    hex: '#ef4444',
    glowHex: '#fecaca',
    rgb: '239, 68, 68',
    lightBg: 'rgba(254, 242, 242, 0.85)',
    lightBorder: 'rgba(252, 165, 165, 0.5)',
    textColor: '#b91c1c',
  },
}

export const STATE_COLOR_LIST: StateColor[] = [
  STATE_COLORS.white,
  STATE_COLORS.purple,
  STATE_COLORS.blue,
  STATE_COLORS.pink,
  STATE_COLORS.green,
  STATE_COLORS.yellow,
  STATE_COLORS.orange,
  STATE_COLORS.red,
]
