import { ColorId, InterpretationCell, MirrorId } from './types'

export const INTERPRETATION_CELLS: Record<MirrorId, Record<ColorId, InterpretationCell>> = {
  core: {
    white: {
      colorId: 'white',
      mirrorId: 'core',
      title: '归零重置的本质',
      meaning: '这件事的核心本质是旧周期的自然终结。最深处的力量在于彻底清空与放下执念，为新格局留白。',
      lightExpression: '内心已具备放手的从容，深知清空才能迎来新生。',
      shadowExpression: '将“放手”误解为无能为力，或迟迟不肯承认旧篇章已然翻过。',
      reflectionQuestion: '如果允许自己彻底放下所有前提假设，你最纯粹的意图是什么？',
      actionSuggestion: '停止对已结束事项的资源追投，允许自己拥有一个空白过渡期。',
      tags: ['清空', '重置', '释怀', '新生'],
      contextScore: { support: 70, tension: 30, urgency: 40, clarity: 85 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'core',
      title: '内观觉察的本质',
      meaning: '这件事本质上是一次深度的内在觉醒。问题的根源不在外界是非，而在你是否敢于直视自己早已洞察的真相。',
      lightExpression: '直觉敏锐清澈，能够穿透表象直达因果本质。',
      shadowExpression: '将直觉当成空想，用外界的繁杂意见自我怀疑与掩耳盗铃。',
      reflectionQuestion: '如果不去寻求任何人的背书与认可，你内心其实早就看清了什么？',
      actionSuggestion: '给自己一段独处沉思的时间，将直觉的真实感知完整记录下来。',
      tags: ['直觉', '看清', '内观', '定力'],
      contextScore: { support: 80, tension: 25, urgency: 30, clarity: 90 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'core',
      title: '真实表达的本质',
      meaning: '这件事的核心在于信息的对齐与真实诉求的传递。打破沉默、坦诚相见是所有转机的原点。',
      lightExpression: '渴望清晰透明，有勇气直面客观事实并平静交流。',
      shadowExpression: '隐瞒关键真实感受，用委婉或回避制造更深的信息断层。',
      reflectionQuestion: '有什么最真实的心声，是你一直没有公开摊在桌面上的？',
      actionSuggestion: '起草一份不带情绪色彩的事实清单，准备一次开诚布公的对话。',
      tags: ['真相', '沟通', '对齐', '透明'],
      contextScore: { support: 75, tension: 40, urgency: 60, clarity: 80 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'core',
      title: '情感共鸣的本质',
      meaning: '这件事的核心在于情感的归属与自我滋养。单凭冰冷的逻辑无法解题，唯有回归热爱与共鸣。',
      lightExpression: '心胸柔软开放，渴望建立温暖、真实、充满信任的连接。',
      shadowExpression: '因害怕受伤而穿上厚重的情感铠甲，将渴望包装成冷漠。',
      reflectionQuestion: '这件事怎样发展，才能让你由衷感到轻盈、被滋养与被接纳？',
      actionSuggestion: '放下一部分苛刻的功利算计，优先倾听自己身心最柔软的感受。',
      tags: ['接纳', '温度', '喜悦', '连接'],
      contextScore: { support: 85, tension: 20, urgency: 35, clarity: 75 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'core',
      title: '结构转化的本质',
      meaning: '这件事的核心在于顺应变化与灵活调整。原有的固定轨道已到瓶颈，生长需要新的支点。',
      lightExpression: '极强的适应力与弹性，愿意推倒重组、顺势迭代。',
      shadowExpression: '机械僵化地固守旧模式，以为只要坚持就能克服结构性缺陷。',
      reflectionQuestion: '如果改变的是解决问题的方法而不是最终追求，会带来什么新转机？',
      actionSuggestion: '尝试打破现有流程中的一个固有环节，进行一次小成本的结构微调。',
      tags: ['迭代', '生长', '变通', '灵活性'],
      contextScore: { support: 80, tension: 35, urgency: 55, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'core',
      title: '理性明辨的本质',
      meaning: '这件事的核心在于建立清晰的边界与客观准则。混乱与纠缠需要理性的剪刀来果断修剪。',
      lightExpression: '条理清晰，具备严谨的权衡分析与取舍魄力。',
      shadowExpression: '陷入利弊推演的死循环，为了寻求所谓的绝对最优解而裹足不前。',
      reflectionQuestion: '按最严苛的核心标准来看，哪一部分是不可妥协的基石，哪一部分纯属干扰？',
      actionSuggestion: '写下一条不可动摇的底线原则，以此作为所有后续分支的唯一筛选器。',
      tags: ['明辨', '理性', '边界', '抉择'],
      contextScore: { support: 75, tension: 45, urgency: 50, clarity: 95 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'core',
      title: '蓄势时机的本质',
      meaning: '这件事的核心在于顺应生命周期的自然节律。当前处于积蓄充能期，强求快速结果只会拔苗助长。',
      lightExpression: '懂得敬畏时机，能够在潜伏期从容蓄力、深度打磨。',
      shadowExpression: '将蓄势当成无所作为的拖延，在浮躁与焦虑中过早释放动能。',
      reflectionQuestion: '如果外部成熟窗口尚未打开，你当下最应该在后台储备什么能力？',
      actionSuggestion: '将精力收缩到打磨基础实力与补足短板上，静候最佳发射窗口。',
      tags: ['时机', '蓄力', '耐心', '等待'],
      contextScore: { support: 70, tension: 40, urgency: 25, clarity: 80 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'core',
      title: '果敢决断的本质',
      meaning: '这件事的核心在于坚决的意志力与不可逆的突破行动。时局已不再需要更多推演，唯有行动能定乾坤。',
      lightExpression: '果敢无畏，能够承担推进责任，以澎湃的执行力撕开突破口。',
      shadowExpression: '盲目用蛮力硬冲，将速度当成方向，引发激烈的反作用力。',
      reflectionQuestion: '如果不再等待万事俱备的虚假安全感，你今天就必须踏出的那一步是什么？',
      actionSuggestion: '在24小时内落实一项实质性的不可逆动作，打破当前的犹豫胶着。',
      tags: ['决断', '行动', '突破', '魄力'],
      contextScore: { support: 80, tension: 50, urgency: 90, clarity: 85 },
    },
  },
  mind: {
    white: {
      colorId: 'white',
      mirrorId: 'mind',
      title: '极简归零的心念',
      meaning: '你的心智正在尝试给所有念头做断舍离，渴望剥离复杂、回归原点的纯粹认知。',
      lightExpression: '不抱成见，以开放的新手心态接纳一切可能性。',
      shadowExpression: '思维产生逃避倾向，用消极虚无主义对抗现实复杂性。',
      reflectionQuestion: '脑海中有哪几个根深蒂固的假设，是时候彻底清空了？',
      actionSuggestion: '将脑中的纷乱念头列在纸上，划掉那些自己无法掌控的部分。',
      tags: ['极简', '去执', '留白', '纯净'],
      contextScore: { support: 70, tension: 25, urgency: 30, clarity: 90 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'mind',
      title: '高维洞察的心念',
      meaning: '你的思维正在以抽离观察者的视角审视全局，洞察事态背后的深层规律与心理循环。',
      lightExpression: '超然物外，不被眼前的得失所绑架，格局宏大。',
      shadowExpression: '过度沉迷形而上的理论剖析，脱离现实地面，缺乏落地推演。',
      reflectionQuestion: '如果跳出当事人的剧本，你在整场互动中观察到了什么重复循环？',
      actionSuggestion: '把当前的困境当成他人的案例来分析，提炼出中立的解决模型。',
      tags: ['观察', '觉察', '宏观', '规律'],
      contextScore: { support: 85, tension: 20, urgency: 35, clarity: 95 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'mind',
      title: '严密求证的心念',
      meaning: '你的思维高度聚焦于事实依据、逻辑链条与清晰的表达结构。',
      lightExpression: '表达精准严密，讲究证据与客观事实，极具说服力。',
      shadowExpression: '过度咬文嚼字，用纯逻辑的辩论掩盖对真实情感的逃避。',
      reflectionQuestion: '你是在用逻辑寻求真相，还是在用逻辑赢下一场争论？',
      actionSuggestion: '用一段不超过100字的精炼陈述，梳理出当下的核心事实与诉求。',
      tags: ['逻辑', '求证', '清晰', '辨析'],
      contextScore: { support: 75, tension: 35, urgency: 50, clarity: 90 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'mind',
      title: '情理交融的心念',
      meaning: '你的思考深度锚定在人际感受、团队温度与彼此的情感认同之上。',
      lightExpression: '极富同理心，能体察各方的处境与心理预期，追求人本价值。',
      shadowExpression: '容易被他人评价或情绪勒索所左右，陷入“讨好型”思考陷阱。',
      reflectionQuestion: '你的考量中，有多少比例是在真正照顾自己的初心，多少是在讨好他人？',
      actionSuggestion: '在思考方案时，将自己的感受与他人同等重要的权重并列考量。',
      tags: ['同理', '人本', '共情', '温和'],
      contextScore: { support: 80, tension: 30, urgency: 40, clarity: 70 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'mind',
      title: '灵活敏捷的心念',
      meaning: '你的大脑正在高速运转，不断构想替代路径、备选方案与策略转折。',
      lightExpression: '思路开阔，不死磕单一路线，总能找到出其不意的解法。',
      shadowExpression: '注意力涣散，主意变动过快，缺乏将一个构想执行到底的定力。',
      reflectionQuestion: '在目前想到的众多调整方案中，哪一个是杠杆率最高、阻力最小的？',
      actionSuggestion: '选定最具可能性的微调切入点，制定3天快速试错计划。',
      tags: ['敏捷', '灵活', '创意', '变通'],
      contextScore: { support: 85, tension: 30, urgency: 60, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'mind',
      title: '批判评估的心念',
      meaning: '你的思维犹如严密的审计器，正在对所有潜在风险、成本与收益进行量化推演。',
      lightExpression: '极度理性客观，能精准识别漏洞，制定滴水不漏的防御策略。',
      shadowExpression: '分析瘫痪（Analysis Paralysis），因追求零风险而无限期推迟结论。',
      reflectionQuestion: '即使只有75%的确定性，你是否愿意允许自己在不确定中起步？',
      actionSuggestion: '为思考设定一个明确的截止时间，到期后必须选出当前最优解。',
      tags: ['理性', '评估', '风控', '权衡'],
      contextScore: { support: 70, tension: 50, urgency: 45, clarity: 95 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'mind',
      title: '审时度势的心念',
      meaning: '你的心智高度关注外部环境的节奏变化与关键时机的窗口期。',
      lightExpression: '战略耐性极高，能够克制盲目出牌的冲动，精确计算出手时刻。',
      shadowExpression: '过度瞻前顾后，在所谓的“等待最佳时机”中渐渐磨灭了锋芒。',
      reflectionQuestion: '什么才是标志着可以全力启动的客观硬信号？',
      actionSuggestion: '明确列出3个启动行动的触发条件（Trigger），条件满足即刻执行。',
      tags: ['节奏', '伺机', '审势', '克制'],
      contextScore: { support: 75, tension: 35, urgency: 30, clarity: 85 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'mind',
      title: '目标导向的心念',
      meaning: '你的思维极具进攻性与结果导向，迫不及待想要穿透所有阻碍达成既定目标。',
      lightExpression: '专注聚焦于突破路径，执行意志如刀锋般锐利坚决。',
      shadowExpression: '急躁求成，容易因看不惯缓慢节奏而产生烦躁与攻击性。',
      reflectionQuestion: '你的这股急切推进劲头，是在解决问题，还是在试图逃避悬而未决的焦灼？',
      actionSuggestion: '把急躁转化为具体的执行清单，一次只死磕一项关键任务。',
      tags: ['聚焦', '推进', '刚决', '目标'],
      contextScore: { support: 80, tension: 55, urgency: 85, clarity: 85 },
    },
  },
  emotion: {
    white: {
      colorId: 'white',
      mirrorId: 'emotion',
      title: '渴望解脱的情绪',
      meaning: '在心底深处，有一种深深渴望卸下重担、彻底松弛、长出一口气的疲倦与解脱感。',
      lightExpression: '感知到内在的释怀与坦然，不再与现实无谓较劲。',
      shadowExpression: '因长期过度消耗而产生的心力枯竭与情感麻木。',
      reflectionQuestion: '想象自己完全从这场拉扯中抽身离去，你的身心是否会涌起一阵轻松？',
      actionSuggestion: '今晚给自己安排完全断联的休息时间，彻底关闭消息打扰。',
      tags: ['释怀', '疲倦', '解脱', '松弛'],
      contextScore: { support: 65, tension: 30, urgency: 20, clarity: 80 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'emotion',
      title: '沉静自若的情绪',
      meaning: '在表层微澜之下，深藏着一种不被外界动荡所侵扰的内在安宁与笃定。',
      lightExpression: '深谙万物自有节律，情绪基线平稳如镜，不易被激怒。',
      shadowExpression: '过于抽离而显得冷漠寡淡，阻断了与他人真实的情感互动。',
      reflectionQuestion: '你能否允许自己安住在这一刻的沉静中，不被外界的风吹草动所惊扰？',
      actionSuggestion: '进行5分钟闭目深呼吸，将注意力从外界收回内在的定心点。',
      tags: ['沉静', '定力', '笃定', '安宁'],
      contextScore: { support: 90, tension: 15, urgency: 15, clarity: 90 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'emotion',
      title: '渴望言说的情绪',
      meaning: '胸口积聚着一份想要被听见、被理解、不吐不快的真实压抑感。',
      lightExpression: '对坦诚交流充满渴望，愿意以柔和真挚的态度袒露心声。',
      shadowExpression: '委屈化为怨气或冷嘲热讽，在压抑与爆发的两极之间摆荡。',
      reflectionQuestion: '如果放下所有指责与自卫，你最想温柔说出的心里感受是什么？',
      actionSuggestion: '找一个值得信赖的朋友或在日记里，将未曾说出的话不加评判地宣泄出来。',
      tags: ['倾诉', '压抑', '真实', '呼唤'],
      contextScore: { support: 70, tension: 50, urgency: 65, clarity: 75 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'emotion',
      title: '柔软渴望的情绪',
      meaning: '内心深处细腻敏感，极度渴望被温柔以待、获得理解、归属与支持。',
      lightExpression: '善解人意，充满善意与温润的爱意，能给周围人带来抚慰。',
      shadowExpression: '对冷遇或否定过度敏感，容易陷入情绪内耗或委曲求全。',
      reflectionQuestion: '你是否在等待别人给予你关怀？如何先在当下温柔地接纳自己？',
      actionSuggestion: '做一件单纯取悦自己身心的小事，为自己充填温暖的心理能量。',
      tags: ['细腻', '柔软', '关怀', '温度'],
      contextScore: { support: 85, tension: 25, urgency: 30, clarity: 70 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'emotion',
      title: '跃跃欲试的情绪',
      meaning: '情绪底色充满好奇、生机与对新可能的渴望，停滞会让你感到窒息。',
      lightExpression: '生机勃勃，对探索未知充满热忱，能够自发调整心态。',
      shadowExpression: '三分钟热度，容易被新鲜事物分散注意，缺乏耐得住寂寞的韧性。',
      reflectionQuestion: '当前的情绪是在催促你走向新生，还是在逃避眼前的沉重责任？',
      actionSuggestion: '为自己引入一项轻量的新尝试，给平淡的局面注入新鲜空气。',
      tags: ['生机', '好奇', '探索', '流动'],
      contextScore: { support: 85, tension: 20, urgency: 55, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'emotion',
      title: '隐约犹疑的情绪',
      meaning: '潜意识中存在对失控或犯错的担忧，情绪在追求完美与害怕遗憾之间摇摆。',
      lightExpression: '敬畏风险，谨慎周全，不盲目冲动行事。',
      shadowExpression: '自我批判苛刻，被假想的糟糕后果裹挟，身心长期处于防御紧绷。',
      reflectionQuestion: '如果最坏的情况发生，你其实完全有能力承受与重组，对吗？',
      actionSuggestion: '写下你最恐惧发生的事情，并为每项恐惧写出一句具体的应对预案。',
      tags: ['谨慎', '犹疑', '紧绷', '防备'],
      contextScore: { support: 60, tension: 60, urgency: 40, clarity: 85 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'emotion',
      title: '蓄力张力的情绪',
      meaning: '犹如起跑线上等待发令枪的选手，内心充斥着既想冲刺又必须克制的张力。',
      lightExpression: '积攒了充沛的情绪势能，能把躁动转化为沉稳的蓄势。',
      shadowExpression: '因等待而产生焦虑焦灼，在急不可耐中容易情绪失控。',
      reflectionQuestion: '能否将内心的微躁感，视为势能正在深层积聚的良性信号？',
      actionSuggestion: '通过适度的身体运动消耗多余的焦虑生理电荷，找回内心的沉静。',
      tags: ['张力', '蓄势', '躁动', '隐忍'],
      contextScore: { support: 70, tension: 50, urgency: 45, clarity: 75 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'emotion',
      title: '激情澎湃的情绪',
      meaning: '一股灼热的动力、愤怒、渴望或坚决意志在体内激荡，迫切需要宣泄与破局。',
      lightExpression: '满腔热血，敢于直面冲突，具备极强的情感感染力与勇气。',
      shadowExpression: '情绪冲动易怒，容易在情绪上头时说出伤人或不可挽回的过激之言。',
      reflectionQuestion: '这股炽热的火焰，应该用来点亮破局的灯塔，还是用来焚烧当下的关系？',
      actionSuggestion: '在情绪最强烈的当下不要立刻做重大回应，等待15分钟后再行定夺。',
      tags: ['激情', '冲劲', '勇气', '炽热'],
      contextScore: { support: 75, tension: 65, urgency: 95, clarity: 75 },
    },
  },
  action: {
    white: {
      colorId: 'white',
      mirrorId: 'action',
      title: '减法断舍的行动',
      meaning: '你目前的行动策略侧重于主动暂停、休整、剥离冗余与终止无效益的项目。',
      lightExpression: '敢于断舍离，懂得以退为进、保留核心元气。',
      shadowExpression: '全面停摆，用被动怠工或彻底放弃来逃避应有的担当。',
      reflectionQuestion: '目前正在推进的事项中，哪一项其实早就该体面地按下终止键？',
      actionSuggestion: '从你的待办清单中坚决划掉两项低价值事项，不再投入精力。',
      tags: ['减法', '断舍', '休整', '退出'],
      contextScore: { support: 70, tension: 30, urgency: 35, clarity: 85 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'action',
      title: '复盘诊断的行动',
      meaning: '你目前的行动以观察、调研、复盘和系统性诊断为主，暂不急于盲目扩张。',
      lightExpression: '谋定而后动，先找准病灶再精准施策。',
      shadowExpression: '无休止的调研与论证，将研究本身变成了拖延行动的掩体。',
      reflectionQuestion: '你的调研是否已经获得了足够的信号？何时正式切入执行？',
      actionSuggestion: '将当前的分析结论整理成一份明确的行动路线图，设定启动节点。',
      tags: ['复盘', '调研', '诊断', '谋划'],
      contextScore: { support: 80, tension: 25, urgency: 40, clarity: 90 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'action',
      title: '沟通对齐的行动',
      meaning: '你目前的行动重在发起对话、撰写方案、对外宣讲与各方信息的互通对齐。',
      lightExpression: '沟通积极透明，善于通过对话消弭隔阂、促成合作。',
      shadowExpression: '空谈大于实干，停留在言语的频繁交流中，缺乏实质成果交付。',
      reflectionQuestion: '在所有的沟通之后，实际的交付成果是否正在稳步落地？',
      actionSuggestion: '在下次沟通结束时，当场与对方敲定具体的落实时间表与负责人。',
      tags: ['沟通', '对齐', '输出', '协商'],
      contextScore: { support: 75, tension: 35, urgency: 65, clarity: 85 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'action',
      title: '维护关系的行动',
      meaning: '你目前的行动以增进信任、化解摩擦、关心伙伴与营造融洽环境为重心。',
      lightExpression: '以柔克刚，善于积累人际善意与协同势能。',
      shadowExpression: '为了顾及情面而在关键原则上无底线退让，损害了整体进展。',
      reflectionQuestion: '在呵护关系的同时，你是否捍卫了事项推进的底线与原则？',
      actionSuggestion: '向支持你的伙伴表达一次真诚的感谢，同时明确下一步的工作配合要求。',
      tags: ['关怀', '维护', '融洽', '协同'],
      contextScore: { support: 80, tension: 20, urgency: 45, clarity: 75 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'action',
      title: '小步快跑的行动',
      meaning: '你目前的行动以敏捷微调、快速迭代、边干边改为主要特征。',
      lightExpression: '行动敏捷，具备出色的抗风险能力与环境自适应力。',
      shadowExpression: '动作变形频繁，朝令夕改，导致团队或自身缺乏稳定的发力重心。',
      reflectionQuestion: '最近做出的这些微调，是否都收敛于同一个核心目标？',
      actionSuggestion: '固定核心指标不变，允许自己在执行手法上进行为期一周的快速试错。',
      tags: ['迭代', '试错', '敏捷', '调整'],
      contextScore: { support: 85, tension: 30, urgency: 70, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'action',
      title: '流程规范的行动',
      meaning: '你目前的行动重在建立标准、梳理流程、设立考核与严控执行质量。',
      lightExpression: '执行标准极高，通过体系化与制度化确保成果的稳定与可复现。',
      shadowExpression: '陷入繁文缛节与形式主义，僵化的规范反而扼杀了现场的应变活力。',
      reflectionQuestion: '你的流程规范是在为高效推进赋能，还是成为了阻碍速度的枷锁？',
      actionSuggestion: '精简现有流程中的冗余审批或核对节点，保留最核心的质量关卡。',
      tags: ['标准', '规范', '体系', '管控'],
      contextScore: { support: 75, tension: 45, urgency: 55, clarity: 90 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'action',
      title: '深耕沉淀的行动',
      meaning: '你目前的行动以练内功、储备弹药、打磨产品或静待时机为主。',
      lightExpression: '能耐住寂寞，把底层地基打得无比扎实，厚积薄发。',
      shadowExpression: '以沉淀为名掩盖对直面市场检验的恐惧，迟迟不敢亮剑。',
      reflectionQuestion: '底层的储备是否已达到可以推向外界检验的标准？',
      actionSuggestion: '设定一个明确的公开发布或测试日期，倒逼当下的沉淀转化为成果。',
      tags: ['沉淀', '打磨', '储备', '内功'],
      contextScore: { support: 75, tension: 35, urgency: 35, clarity: 85 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'action',
      title: '高压推进的行动',
      meaning: '你目前的行动以高速冲刺、硬碰硬攻坚与强力压制不确定性为特征。',
      lightExpression: '执行速度极快，气势如虹，能以惊人的动能冲破重重关卡。',
      shadowExpression: '强推蛮干，引发剧烈的环境摩擦与团队疲惫，埋下隐患。',
      reflectionQuestion: '目前的高压推进是在创造顺畅的突破，还是在引发更大的阻力墙？',
      actionSuggestion: '在推进的同时，安排专人或留出专门精力去复盘和稳固战果。',
      tags: ['强推', '攻坚', '冲刺', '突破'],
      contextScore: { support: 80, tension: 65, urgency: 95, clarity: 80 },
    },
  },
  relation: {
    white: {
      colorId: 'white',
      mirrorId: 'relation',
      title: '自然淡出的关系',
      meaning: '某段人际关系或合作契约正在自然走入尾声，双方的需求与轨迹已出现分化。',
      lightExpression: '体面放手，感恩彼此曾经的陪伴，互不相欠地道别。',
      shadowExpression: '怨恨纠缠，不愿承认缘分已尽，用冷战或折磨消耗最后的善意。',
      reflectionQuestion: '面对这段已经完成历史使命的关系，你是否能给予彼此体面的退场？',
      actionSuggestion: '礼貌、温和且坚定地结束不再适合的合作或过度依赖的交际。',
      tags: ['放手', '退场', '缘尽', '解约'],
      contextScore: { support: 65, tension: 35, urgency: 40, clarity: 85 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'relation',
      title: '互为镜像的关系',
      meaning: '对方就像一面清澈的镜子，如实映照出你自己身上尚未觉察的盲点与模式。',
      lightExpression: '将人际摩擦视为自我修行的宝贵契机，从中照见自我。',
      shadowExpression: '将所有问题投射并归咎于对方，拒绝直视自己在这场关系中的责任。',
      reflectionQuestion: '对方身上最令你反感或执着的特质，揭示了你自身哪部分未整合的阴影？',
      actionSuggestion: '停止批判对方，反观并写下自己在互动中所扮演的模式角色。',
      tags: ['镜像', '投射', '洞见', '自省'],
      contextScore: { support: 80, tension: 40, urgency: 30, clarity: 90 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'relation',
      title: '急需对齐的关系',
      meaning: '关系中存在关键的言语隔阂、误会或未经明确确认的隐形契约。',
      lightExpression: '愿意主动坐下来，用清晰、平静、无攻击性的语言解开误会。',
      shadowExpression: '双方都在互相猜测，用沉默和试探拉大彼此的心智距离。',
      reflectionQuestion: '你们之间哪一项关键期待，至今从未用明确的书面或言语确立过？',
      actionSuggestion: '主动发起一次专门的对齐会议，将彼此的权责与期待逐一摊开确认。',
      tags: ['对齐', '澄清', '沟通', '契约'],
      contextScore: { support: 75, tension: 50, urgency: 70, clarity: 85 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'relation',
      title: '深厚共鸣的关系',
      meaning: '关系场域充满天然的默契、善意与彼此扶持，是宝贵的情感绿洲。',
      lightExpression: '彼此全然信任，能够敞开心扉，在协作中产生高频的能量共振。',
      shadowExpression: '为了维持脆弱的表面和谐而不敢指出彼此的真实问题，成为同谋。',
      reflectionQuestion: '如何在这份融洽的信任基础上，建立更加建设性的客观反馈机制？',
      actionSuggestion: '向对方表达深度的信任与支持，共同庆祝阶段性的小成果。',
      tags: ['共鸣', '信任', '默契', '温情'],
      contextScore: { support: 90, tension: 15, urgency: 35, clarity: 80 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'relation',
      title: '重构演变的关系',
      meaning: '彼此的角色定位与分工正在经历动态的重组，旧有的相处模板已被打破。',
      lightExpression: '乐于探索更健康的新型协作模式，彼此赋能、共同进化。',
      shadowExpression: '在角色转换中争夺主导权，因权责模糊而产生持续的摩擦与内耗。',
      reflectionQuestion: '对于现在的你们来说，怎样的新分工与边界才是最舒适高效的？',
      actionSuggestion: '重新起草一份新的合作规则，明确各自在全新阶段的角色定义。',
      tags: ['重构', '演变', '新规则', '赋能'],
      contextScore: { support: 80, tension: 40, urgency: 60, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'relation',
      title: '公事公办的关系',
      meaning: '关系建立在清晰的契约、利益绑定与明确的专业规则之上。',
      lightExpression: '界限分明，权责清晰，以职业化水准推进合作，高效透明。',
      shadowExpression: '过分冷酷严苛，缺乏人情味，在突发困境时缺乏相互兜底的韧性。',
      reflectionQuestion: '在坚守专业原则的同时，能否多给予对方一丝人性化的理解？',
      actionSuggestion: '严格按照合同或约定办事，避免因私交情面而妥协关键底线。',
      tags: ['界限', '专业', '契约', '公事'],
      contextScore: { support: 75, tension: 40, urgency: 50, clarity: 95 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'relation',
      title: '节奏脱节的关系',
      meaning: '你与对方在推进节奏、认知深度或准备程度上存在时间差，一方在等另一方。',
      lightExpression: '理解彼此节奏的差异，给予对方合理的成长与决策空间。',
      shadowExpression: '因对方的滞后而焦躁催促，将自己的时间表强加于他人。',
      reflectionQuestion: '在对方准备就绪之前，你如何先做好自己的部分，不把精力全耗在催促上？',
      actionSuggestion: '给对方一个清晰的等待截止日期，在此期间各自独立推进前置工作。',
      tags: ['时间差', '等待', '节奏', '耐心'],
      contextScore: { support: 70, tension: 50, urgency: 40, clarity: 80 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'relation',
      title: '张力对抗的关系',
      meaning: '关系中存在明显的竞争张力、权力较量或直接的观点碰撞。',
      lightExpression: '直面竞争与冲突，将摩擦转化为倒逼彼此拿出真本领的催化剂。',
      shadowExpression: '陷入零和博弈与你死我活的情绪争斗，双双两败俱伤。',
      reflectionQuestion: '你是在为事情的真正结果而战，还是在为了自己的面子与胜负欲而争？',
      actionSuggestion: '将焦点从人际对抗转移到客观事实与共同利益上，寻找第三条道路。',
      tags: ['竞争', '碰撞', '博弈', '张力'],
      contextScore: { support: 65, tension: 75, urgency: 85, clarity: 85 },
    },
  },
  reality: {
    white: {
      colorId: 'white',
      mirrorId: 'reality',
      title: '出现留白的现实',
      meaning: '外部现实环境呈现出罕见的空白期，旧规则瓦解，新空间正等待被定义。',
      lightExpression: '拥有自由挥洒的广阔蓝海，没有历史包袱的羁绊。',
      shadowExpression: '面对一片空白不知所措，缺乏无中生有的构建勇气。',
      reflectionQuestion: '面对外部这片完全空白的新领域，你打算写下什么样的第一笔？',
      actionSuggestion: '抢占先机，率先在空白领域确立自己的标准与代表作。',
      tags: ['蓝海', '空白', '无羁绊', '新空间'],
      contextScore: { support: 75, tension: 25, urgency: 50, clarity: 85 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'reality',
      title: '信号隐晦的现实',
      meaning: '外部大势复杂晦涩，表面数据具备迷惑性，必须具备洞察底层趋势的眼光。',
      lightExpression: '能从微弱的线索中捕捉到未来的风向，未雨绸缪。',
      shadowExpression: '被表面的喧嚣所蒙蔽，做出误判全局的盲从决策。',
      reflectionQuestion: '有哪些被大众普遍忽视的微弱信号，正在预示着未来的转变？',
      actionSuggestion: '减少对表面大众资讯的摄入，深入研究底层原生数据与行业底层逻辑。',
      tags: ['趋势', '信号', '大势', '隐微'],
      contextScore: { support: 80, tension: 35, urgency: 45, clarity: 90 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'reality',
      title: '信息嘈杂的现实',
      meaning: '外部环境信息过载，舆论纷纷扰扰，各方声音相互冲突、真假难辨。',
      lightExpression: '具备极强的信息甄别与降噪能力，只抓关键信源。',
      shadowExpression: '被过载的信息搞得焦虑迷失，在众说纷纭中失去了自己的主心骨。',
      reflectionQuestion: '哪些外部的声音与评论是你应当立刻屏蔽的噪音？',
      actionSuggestion: '主动切断3个干扰性强的信息渠道，建立纯净的决策环境。',
      tags: ['信息过载', '降噪', '信源', '舆论'],
      contextScore: { support: 65, tension: 55, urgency: 60, clarity: 75 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'reality',
      title: '友善包容的现实',
      meaning: '外部环境对你呈现出善意、包容与支持的氛围，土壤温润，适宜生长。',
      lightExpression: '能充分调动外部现有的善意资源与人际红利，事半功倍。',
      shadowExpression: '在温水煮青蛙的舒适区中丧失警惕，缺乏抗风险的后手准备。',
      reflectionQuestion: '如何善用当前环境赋予你的善意与支持，将其转化为长远的护城河？',
      actionSuggestion: '主动借力外部友好的环境资源，加速推进核心项目的阶段性跨越。',
      tags: ['红利', '友好', '包容', '借力'],
      contextScore: { support: 90, tension: 15, urgency: 40, clarity: 80 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'reality',
      title: '瞬息万变的现实',
      meaning: '外部市场与政策条件剧烈变动，原有的计划必须具备极高的自我迭代能力。',
      lightExpression: '极具敏锐度，能够在变局中快速发现新风口与新结构。',
      shadowExpression: '固守陈规，企图用一套僵化的老办法去应对完全变样的新世界。',
      reflectionQuestion: '如果目前的外部规则在一周后再次变动，你的方案是否依然具备生存力？',
      actionSuggestion: '为核心方案设计一份“Plan B”应急预案，提高抗压弹性和冗余度。',
      tags: ['变局', '风口', '弹性', '迭代'],
      contextScore: { support: 80, tension: 45, urgency: 75, clarity: 80 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'reality',
      title: '硬性约束的现实',
      meaning: '外部在预算、时间周期、合规政策或资源上限上存在坚硬不可逾越的边界。',
      lightExpression: '尊重客观规律，善于在戴着镣铐的严苛限制中跳出最惊艳的舞蹈。',
      shadowExpression: '抱有侥幸心理，试图硬闯客观红线，最终撞得头破血流。',
      reflectionQuestion: '与其抱怨客观限制，如何将这些不可改变的限制变成你的独特优势？',
      actionSuggestion: '梳理出所有的硬性限制红线，将有限的资源精准聚焦在合规的核心路径上。',
      tags: ['约束', '硬指标', '红线', '克制'],
      contextScore: { support: 70, tension: 60, urgency: 65, clarity: 95 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'reality',
      title: '周期筑底的现实',
      meaning: '外部大环境正处于宏观周期的蓄势与筑底阶段，整体流动性与推进速度偏慢。',
      lightExpression: '顺应周期律动，在低谷期潜心沉淀，等待周期的向上反转。',
      shadowExpression: '在寒冬中盲目消耗核心弹药，过早将筹码孤注一掷。',
      reflectionQuestion: '在宏观慢周期中，你该如何做好“深淘滩、低作堰”的防守工作？',
      actionSuggestion: '做好现金流与精力的严密防御，将任务拆解为低消耗的稳步推进。',
      tags: ['周期', '筑底', '大势', '稳健'],
      contextScore: { support: 70, tension: 45, urgency: 30, clarity: 85 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'reality',
      title: '急迫倒逼的现实',
      meaning: '外部窗口期转瞬即逝，竞争对手或现实倒计时正在迫使你必须迅速响应。',
      lightExpression: '在紧迫情势下展现出强大的执行效率，抢占先机。',
      shadowExpression: '被外部的紧迫感冲昏头脑，盲目慌乱出手，出现致命破绽。',
      reflectionQuestion: '在外部倒逼的压力下，哪一个关键动作能真正扭转被动局面？',
      actionSuggestion: '砍掉所有枝节，将全部力量集中到阻击核心威胁的最紧急防线上。',
      tags: ['窗口期', '紧迫', '先机', '倒逼'],
      contextScore: { support: 70, tension: 70, urgency: 95, clarity: 85 },
    },
  },
  block: {
    white: {
      colorId: 'white',
      mirrorId: 'block',
      title: '难舍沉没成本的阻碍',
      meaning: '最大的卡点在于舍不得沉没成本、旧有荣誉或已经名存实亡的旧关系，迟迟不肯翻篇。',
      lightExpression: '内心已经清晰知道该放手，只是需要最后一点决断的勇气。',
      shadowExpression: '自欺欺人，企图用更多的投入来拯救一个早已注定结束的死局。',
      reflectionQuestion: '你还在拼命抓着什么早已失去生命力的事情，不肯放手？',
      actionSuggestion: '承认旧周期的结束，果断止损，彻底清空账面与心理负累。',
      tags: ['沉没成本', '执念', '不肯放手', '止损'],
      contextScore: { support: 40, tension: 70, urgency: 60, clarity: 80 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'block',
      title: '过度思辨内耗的阻碍',
      meaning: '最大的卡点在于空想大于行动，用无休止的自我反思和推演来逃避真实的现实碰撞。',
      lightExpression: '理论储备极其丰富，只是缺少将认知落地的现实通道。',
      shadowExpression: '思想的巨人、行动的矮子，陷入精神内耗与高维傲慢中裹足不前。',
      reflectionQuestion: '哪件事你其实早已想得清清楚楚，只是害怕面对现实中的粗糙与不完美？',
      actionSuggestion: '停止进一步的理论推演，逼迫自己去完成一件最粗糙的实际交付。',
      tags: ['内耗', '空想', '逃避现实', '过度思辨'],
      contextScore: { support: 45, tension: 65, urgency: 50, clarity: 75 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'block',
      title: '回避关键真实的阻碍',
      meaning: '最大的卡点在于自我言语审查或息事宁人的沉默，不敢把真正的问题挑明摊开。',
      lightExpression: '深谙沟通的重要性，只要鼓起勇气就能打破死局。',
      shadowExpression: '为了虚假的表面和平而把委屈吞下，导致猜忌与误会持续发酵。',
      reflectionQuestion: '为了维持短暂的表面和谐，你正在给未来埋下怎样不可承受的地雷？',
      actionSuggestion: '不再拐弯抹角，找机会用最直接、诚恳的话语将核心问题点破。',
      tags: ['回避', '沉默', '隐瞒真实', '虚假和平'],
      contextScore: { support: 40, tension: 75, urgency: 75, clarity: 70 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'block',
      title: '过度讨好认同的阻碍',
      meaning: '最大的卡点在于过度在意他人的评价与认可，把决策的主导权交给了外部的情感反馈。',
      lightExpression: '拥有一颗渴望连接的热忱之心，只需将边界重新立稳。',
      shadowExpression: '害怕被排斥、害怕冲突，在讨好与妥协中彻底丢失了自我原则。',
      reflectionQuestion: '你究竟还在试图获得谁的赞许，以至于不敢坚持自己的正确主张？',
      actionSuggestion: '在下次面对不合理要求时，练习平静且坚决地说一声“不”。',
      tags: ['讨好', '怕冲突', '缺乏边界', '认同成瘾'],
      contextScore: { support: 45, tension: 65, urgency: 50, clarity: 65 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'block',
      title: '频繁变换方向的阻碍',
      meaning: '最大的卡点在于一遇到攻坚克难就习惯性地调转方向，用“探索新方向”逃避深度承诺。',
      lightExpression: '头脑极其灵活，只要把灵活性用于优化路径而非更换目标。',
      shadowExpression: '浅尝辄止，项目总是开花不结果，缺乏把一口井挖穿的定力。',
      reflectionQuestion: '你是在真正战略性优化，还是在遇到硬骨头时习惯性退缩换赛道？',
      actionSuggestion: '给当前的方向设立一个不可动摇的坚守期限，在此期间绝不允许更换目标。',
      tags: ['摇摆', '逃避承诺', '浅尝辄止', '缺乏定力'],
      contextScore: { support: 40, tension: 70, urgency: 65, clarity: 70 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'block',
      title: '完美主义分析瘫痪的阻碍',
      meaning: '最大的卡点在于过分苛求100%的确定性与零风险，严苛的理性反而扼杀了行动生机。',
      lightExpression: '具备极佳的风控敏锐度，只需把风控转化为保障而非借口。',
      shadowExpression: '吹毛求疵，对任何不确定性过敏，把大量时间浪费在无谓的推演上。',
      reflectionQuestion: '追求绝对完美的背后，是不是你对犯错与丢脸的极度恐惧？',
      actionSuggestion: '树立“先完成再完美”的心态，允许第一版成果存在30%的瑕疵。',
      tags: ['完美主义', '分析瘫痪', '风控过敏', '苛求确定'],
      contextScore: { support: 40, tension: 75, urgency: 55, clarity: 80 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'block',
      title: '借口等待拖延的阻碍',
      meaning: '最大的卡点在于将“等待时机”变成了消极拖延的遮羞布，在被动观望中耗尽了势能。',
      lightExpression: '深知时机的重要性，只需设定清晰的触发条件打破观望。',
      shadowExpression: '温水煮青蛙，看着机会之窗缓缓关闭却依然找各种借口不出手。',
      reflectionQuestion: '这真的是客观时机未到，还是你在逃避迈出第一步的责任？',
      actionSuggestion: '不要再等所谓的完美时机，今天就主动迈出打破停滞的第一步。',
      tags: ['拖延', '借口等待', '被动观望', '消极停滞'],
      contextScore: { support: 35, tension: 70, urgency: 70, clarity: 75 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'block',
      title: '蛮力硬推硬撞的阻碍',
      meaning: '最大的卡点在于固执地使用强攻硬碰的方式对抗现实，把焦躁当成了魄力，引发巨大反弹。',
      lightExpression: '拥有无可匹敌的勇气与冲劲，只需把发力姿态从强攻改为巧劲。',
      shadowExpression: '对已经锁死的门用头硬撞，身心俱疲的同时把周围局面搞得更加恶化。',
      reflectionQuestion: '你在哪里是在与客观规律硬刚，而不是看清规律、改换结构顺势而为？',
      actionSuggestion: '立刻停止在死胡同里的硬碰硬，后退一步，寻找侧面的通畅切入点。',
      tags: ['硬碰硬', '蛮干', '焦躁强推', '反作用力'],
      contextScore: { support: 40, tension: 90, urgency: 85, clarity: 70 },
    },
  },
  key: {
    white: {
      colorId: 'white',
      mirrorId: 'key',
      title: '释放之钥（白）',
      meaning: '彻底清空旧账，归零重置。卸下过期的心理包袱，一身轻松地开启新旅程。',
      lightExpression: '以退为进，通过彻底放手重获内在的主动权与浩瀚空间。',
      shadowExpression: '谨防在清空之后陷入迷茫虚无，要记得为新篇章设立意图。',
      reflectionQuestion: '如果卸下所有过去的包袱与预设，你最想走向哪里？',
      actionSuggestion: '举办一个属于自己的告别仪式，正式宣布旧阶段的终结与归零。',
      tags: ['归零', '放下', '重置', '轻装前行'],
      contextScore: { support: 90, tension: 20, urgency: 60, clarity: 95 },
    },
    purple: {
      colorId: 'purple',
      mirrorId: 'key',
      title: '觉察之钥（紫）',
      meaning: '抽离当前剧情，从更高维度的观察者视角看清全局规律，找回内观直觉的定力。',
      lightExpression: '看清模式本身，就能瞬间化解蛮力无法解决的根本难题。',
      shadowExpression: '看清规律后要回到现实落实，切莫停留在高高在上的评判中。',
      reflectionQuestion: '你内心那个最清醒的旁观者，此刻给出的最朴素的指引是什么？',
      actionSuggestion: '每天留出10分钟进行静心复盘，校准自己的内在航线。',
      tags: ['洞察', '高维', '直觉', '看清真相'],
      contextScore: { support: 95, tension: 15, urgency: 50, clarity: 95 },
    },
    blue: {
      colorId: 'blue',
      mirrorId: 'key',
      title: '表达之钥（蓝）',
      meaning: '坦诚、精准、不带情绪地讲出客观事实与真实心声，打破信息孤岛。',
      lightExpression: '一次毫无保留的真实对话，能够瞬间解开数月的拉扯与猜忌。',
      shadowExpression: '表达要注重倾听与对齐，避免变成单方面的输出宣泄。',
      reflectionQuestion: '你今天可以勇敢讲出的最清晰直接、不加掩饰的一句话是什么？',
      actionSuggestion: '预约一次关键的面对面沟通，心平气和地对齐双方的核心诉求。',
      tags: ['坦诚', '直面', '对齐共识', '精准发声'],
      contextScore: { support: 90, tension: 30, urgency: 80, clarity: 90 },
    },
    pink: {
      colorId: 'pink',
      mirrorId: 'key',
      title: '愉悦之钥（粉）',
      meaning: '找回内心的热爱、温度与轻盈，用柔软包容化解僵局，在享受过程中破局。',
      lightExpression: '当你能从过程中汲取滋养时，外界的阻力会自然而然地消解。',
      shadowExpression: '保持温和的同时，不要遗忘关键目标的落地执行。',
      reflectionQuestion: '如何让当下的推进过程重新变得温暖、有趣且令人享受？',
      actionSuggestion: '在推进中加入人文关怀与激励环节，让彼此在被赋能的状态下前行。',
      tags: ['滋养', '柔软', '温度', '享受过程'],
      contextScore: { support: 90, tension: 15, urgency: 45, clarity: 80 },
    },
    green: {
      colorId: 'green',
      mirrorId: 'key',
      title: '转化之钥（绿）',
      meaning: '调转方向与结构，改变方法而非强攻目标。顺应阻力，借力打力。',
      lightExpression: '方向微调5度，未来的航线就能抵达完全不同的辽阔风景。',
      shadowExpression: '调整结构时要稳住基本盘，切忌盲目大拆大建。',
      reflectionQuestion: '如果改变的是解决的手法而不是最终的目标，最优雅的解法是什么？',
      actionSuggestion: '立即重构当前的执行架构，用更轻量灵活的路径替代笨重的方案。',
      tags: ['结构调整', '变通', '顺势而为', '优雅破局'],
      contextScore: { support: 95, tension: 25, urgency: 75, clarity: 90 },
    },
    yellow: {
      colorId: 'yellow',
      mirrorId: 'key',
      title: '明辨之钥（黄）',
      meaning: '设立清晰明确的评估标准，砍掉冗余，理性聚焦，以果断的边界定夺一切。',
      lightExpression: '清晰的底线能够瞬间消除所有犹豫，立即带来坚定的推进动能。',
      shadowExpression: '立下规则后就要坚决执行，切莫在实施过程中反复妥协。',
      reflectionQuestion: '立下哪一条清晰的原则，能让你当下的选择变得极度简单明了？',
      actionSuggestion: '制定一份非黑即白的筛选规则表，不符合标准的事项一律坚决排除。',
      tags: ['理性决断', '立边界', '清晰准则', '精准取舍'],
      contextScore: { support: 90, tension: 35, urgency: 70, clarity: 100 },
    },
    orange: {
      colorId: 'orange',
      mirrorId: 'key',
      title: '时机之钥（橙）',
      meaning: '耐住性子、深度蓄势，等待势能汇聚的最佳窗口。顺应自然的波浪，厚积薄发。',
      lightExpression: '在最恰当的时机出手，能够以最小的力气收获最大的成果。',
      shadowExpression: '蓄势期间要做好充分准备，不可懈怠，确保机会来临时一击即中。',
      reflectionQuestion: '当关键的时机窗口打开时，你将以怎样的绝对优势果断出手？',
      actionSuggestion: '停止在时机未到时的无谓内耗，把所有精力投入到核心实力的打磨上。',
      tags: ['蓄力', '时机窗口', '耐心深耕', '一击即中'],
      contextScore: { support: 85, tension: 25, urgency: 40, clarity: 90 },
    },
    red: {
      colorId: 'red',
      mirrorId: 'key',
      title: '决断之钥（红）',
      meaning: '全力以赴，迈出不可逆的关键一步。用坚决的执行力定乾坤，破除一切疑虑。',
      lightExpression: '唯有行动能创造真实的引力，用坚决的推进打破一切拖延与猜测。',
      shadowExpression: '推进时注意观察反馈，确保行动力聚焦在核心靶心上。',
      reflectionQuestion: '哪一项果敢的行动，能从根本上重塑眼下的被动局面？',
      actionSuggestion: '不要再等任何人批准，今天就执行那个最具决定性的关键动作。',
      tags: ['雷厉风行', '坚决执行', '破局落地', '不可逆'],
      contextScore: { support: 90, tension: 45, urgency: 100, clarity: 90 },
    },
  },
}
