import { MirrorId, MirrorPosition } from './types'

export const MIRROR_POSITIONS: Record<MirrorId, MirrorPosition> = {
  core: {
    id: 'core',
    index: 1,
    code: '01',
    name: '核心',
    subtitle: '事情真正的本质',
    description: '这件事最底层的动力源与核心本质。',
    guidePrompt: '当下事件的真正核心在哪里？',
  },
  mind: {
    id: 'mind',
    index: 2,
    code: '02',
    name: '心念',
    subtitle: '你如何理解这件事',
    description: '你的主观假设、思维模式与心理认知。',
    guidePrompt: '你的思维正在怎样构建当下的情境？',
  },
  emotion: {
    id: 'emotion',
    index: 3,
    code: '03',
    name: '情绪',
    subtitle: '没有说出口的感受',
    description: '深层潜意识感受、身体直觉与情绪潜流。',
    guidePrompt: '在理智之下，真实的感受是什么？',
  },
  action: {
    id: 'action',
    index: 4,
    code: '04',
    name: '行动',
    subtitle: '你目前正在做什么',
    description: '你目前的行为节奏、发力方式与执行状态。',
    guidePrompt: '你当前的具体行动处于何种节奏？',
  },
  relation: {
    id: 'relation',
    index: 5,
    code: '05',
    name: '人际',
    subtitle: '关系层面的相互影响',
    description: '关键人际场域、彼此期待与隐形互动。',
    guidePrompt: '谁或什么样的关系正在深刻影响局面？',
  },
  reality: {
    id: 'reality',
    index: 6,
    code: '06',
    name: '现实',
    subtitle: '外部客观事实与条件',
    description: '外部资源、环境约束与不可逆的硬性事实。',
    guidePrompt: '当下的现实客观边界是什么？',
  },
  block: {
    id: 'block',
    index: 7,
    code: '07',
    name: '阻碍',
    subtitle: '最大的认知盲区',
    description: '消耗能量的关键堵点或被忽视的卡点。',
    guidePrompt: '当前阻碍能量流动的症结在哪里？',
  },
  key: {
    id: 'key',
    index: 8,
    code: '08',
    name: '钥匙',
    subtitle: '下一步最需要的方向',
    description: '打通全局格局的解锁原则与核心行动矢量。',
    guidePrompt: '能够撬动并调和整体模式的唯一钥匙。',
  },
}

export const MIRROR_POSITION_LIST: MirrorPosition[] = [
  MIRROR_POSITIONS.core,
  MIRROR_POSITIONS.mind,
  MIRROR_POSITIONS.emotion,
  MIRROR_POSITIONS.action,
  MIRROR_POSITIONS.relation,
  MIRROR_POSITIONS.reality,
  MIRROR_POSITIONS.block,
  MIRROR_POSITIONS.key,
]
