import { ColorId, PatternArchetype } from './types'

export const PATTERN_ARCHETYPES: Record<string, PatternArchetype> = {
  FORCE_SHIFT: {
    id: 'FORCE_SHIFT',
    name: 'FORCE → SHIFT',
    chineseName: '强推 → 转化',
    archetype: '结构重组型',
    summary: '你可能正对一个需要调整解决手法的事项，施加了过多的硬碰硬压力。',
    coreAdvice: '不要用力硬推，改换解决结构。',
    deepReflection: '如果改变的是达成的方法而不是最终目标，结果会怎样？',
    tags: ['结构调整', '变通', '顺势而为'],
  },
  THINK_ACT: {
    id: 'THINK_ACT',
    name: 'THINK → ACT',
    chineseName: '思虑 → 决断',
    archetype: '破局执行型',
    summary: '过度的分析推演已经成为逃避行动的掩体，当下唯有执行能打破僵局。',
    coreAdvice: '闭合思考回路，迈出不可逆的关键一步。',
    deepReflection: '你究竟还在等待谁的允许，才肯真正做出这个决定？',
    tags: ['雷厉风行', '坚决执行', '破局'],
  },
  HOLD_RELEASE: {
    id: 'HOLD_RELEASE',
    name: 'HOLD → RELEASE',
    chineseName: '执念 → 释放',
    archetype: '归零清空型',
    summary: '你正背负着已经走完生命周期的旧包袱与旧期待，严重透支了当下的心力。',
    coreAdvice: '清空容器，先给内心留白，方能从容书写新篇。',
    deepReflection: '你究竟在害怕什么，以至于迟迟不肯彻底放手？',
    tags: ['断舍离', '归零', '轻装前行'],
  },
  WAIT_SPEAK: {
    id: 'WAIT_SPEAK',
    name: 'WAIT → SPEAK',
    chineseName: '观望 → 表达',
    archetype: '主动发声型',
    summary: '被动的沉默与观望无法解决误会，必须主动发起坦诚对齐。',
    coreAdvice: '打破沉默，用客观清晰的语言说出事实。',
    deepReflection: '你一直推迟说出口的那句最真实的话是什么？',
    tags: ['坦诚', '精准发声', '对齐共识'],
  },
  FEEL_CLARIFY: {
    id: 'FEEL_CLARIFY',
    name: 'FEEL → CLARIFY',
    chineseName: '感性 → 明辨',
    archetype: '理性梳理型',
    summary: '情绪上的混乱与顾虑，需要极其清晰的理性规则来进行边界划分。',
    coreAdvice: '明确评估标准，做出坚决理性的取舍。',
    deepReflection: '做下哪一个决定，能够立即消除后续十几个不必要的麻烦？',
    tags: ['立边界', '清晰准则', '理性聚焦'],
  },
  SENSE_SPEAK: {
    id: 'SENSE_SPEAK',
    name: 'SENSE → SPEAK',
    chineseName: '内觉 → 表达',
    archetype: '直觉显化型',
    summary: '事情在内心其实早已看得一清二楚，只是尚未转化为公开清晰的对话。',
    coreAdvice: '将内在的清晰洞见，转化为不带攻击性的坦诚沟通。',
    deepReflection: '如果不再害怕冲突，你最想向对方讲明什么？',
    tags: ['洞察', '表达', '清晰'],
  },
  PUSH_PAUSE: {
    id: 'PUSH_PAUSE',
    name: 'PUSH → PAUSE',
    chineseName: '冲动 → 蓄势',
    archetype: '战略深潜型',
    summary: '外部客观条件仍在后台酝酿，急于求成只会过早耗尽宝贵势能。',
    coreAdvice: '不要强行收割，静候果实成熟。',
    deepReflection: '如果等待不是被动懈怠，而是此刻最具杀伤力的策略呢？',
    tags: ['时机', '耐心', '深耕蓄力'],
  },
  END_BEGIN: {
    id: 'END_BEGIN',
    name: 'END → BEGIN',
    chineseName: '终结 → 启程',
    archetype: '新局开启型',
    summary: '旧周期的终点正是新周期的起点，放下昨天的沉没成本才能拥抱崭新天地。',
    coreAdvice: '体面告别过去，全心投入新可能。',
    deepReflection: '如果不再沉湎于昨天的遗憾，明天最吸引你的新冒险是什么？',
    tags: ['新生', '启程', '释怀'],
  },
  CONTROL_FLOW: {
    id: 'CONTROL_FLOW',
    name: 'CONTROL → FLOW',
    chineseName: '掌控 → 顺应',
    archetype: '顺流生长型',
    summary: '过度追求对细节的绝对掌控导致身心俱疲，唯有顺应规律方能借力打力。',
    coreAdvice: '放下微观控制，跟随大势自然流动。',
    deepReflection: '如果你允许事情按照它本身的节律展开，你会有什么新发现？',
    tags: ['顺势', '流动', '借力'],
  },
  DOUBT_VERIFY: {
    id: 'DOUBT_VERIFY',
    name: 'DOUBT → VERIFY',
    chineseName: '犹疑 → 验证',
    archetype: '小步求证型',
    summary: '脑海中的怀疑推演无法得出结论，唯有用最小成本的小步试错去验证事实。',
    coreAdvice: '停止无休止的猜测，用一次轻量实践测出真相。',
    deepReflection: '怎样的一场小测试，能在一天内给你最确凿的答案？',
    tags: ['验证', '试错', '敏捷'],
  },
  REACT_OBSERVE: {
    id: 'REACT_OBSERVE',
    name: 'REACT → OBSERVE',
    chineseName: '应激 → 观照',
    archetype: '高维定力型',
    summary: '应激式的对抗正在消耗你的能量，抽离出来静观底层规律才能找回主导权。',
    coreAdvice: '抽离剧情旋涡，静观底层规律。',
    deepReflection: '如果以十年后的视角审视此刻，什么其实早就显而易见？',
    tags: ['高维', '定力', '觉察'],
  },
  HIDE_EXPRESS: {
    id: 'HIDE_EXPRESS',
    name: 'HIDE → EXPRESS',
    chineseName: '隐匿 → 展现',
    archetype: '坦荡显露型',
    summary: '将真实想法藏匿在面具之下制造了隔阂，唯有坦荡展现才能赢得深度互信。',
    coreAdvice: '摘下防备铠甲，真实地表达自我。',
    deepReflection: '当你敢于展现真实脆弱时，局面会发生怎样的转机？',
    tags: ['真实', '展现', '信任'],
  },
  PLAN_MOVE: {
    id: 'PLAN_MOVE',
    name: 'PLAN → MOVE',
    chineseName: '规划 → 突破',
    archetype: '攻坚破局型',
    summary: '方案已经足够完善，继续停留在规划层面只会错过最佳破局窗口。',
    coreAdvice: '带上现有的方案，坚决投身实战。',
    deepReflection: '把第一步踩实，后续的道路自然会逐一展现。',
    tags: ['实战', '破局', '执行'],
  },
  CHASE_WAIT: {
    id: 'CHASE_WAIT',
    name: 'CHASE → WAIT',
    chineseName: '追逐 → 沉淀',
    archetype: '从容筑底型',
    summary: '盲目追逐外部的风吹草动只会打乱阵脚，沉下心打磨内核才能守株待兔。',
    coreAdvice: '停止盲目追逐，沉心打磨底牌。',
    deepReflection: '把自己的不可替代性做到极致，外部机遇自然会主动汇聚。',
    tags: ['沉淀', '内功', '守拙'],
  },
  PAUSE_ACT: {
    id: 'PAUSE_ACT',
    name: 'PAUSE → ACT',
    chineseName: '停滞 → 亮剑',
    archetype: '蓄力爆发型',
    summary: '观望期已然结束，蓄积已久的势能必须在当下转化为破局的一击。',
    coreAdvice: '时机已至，不再观望，果断出手。',
    deepReflection: '你已经准备得很充分了，是时候亮出你的真本领。',
    tags: ['亮剑', '爆发', '一击即中'],
  },
  FEEL_ACCEPT: {
    id: 'FEEL_ACCEPT',
    name: 'FEEL → ACCEPT',
    chineseName: '抗拒 → 接纳',
    archetype: '温和滋养型',
    summary: '与自己的感受较劲只会带来剧烈内耗，全然接纳并温柔对待才是力量源泉。',
    coreAdvice: '柔化防备，从接纳与自爱中获取动力。',
    deepReflection: '如何在你筑起高墙的地方，重新注入一份轻盈与温度？',
    tags: ['接纳', '滋养', '自爱'],
  },
  CONFUSE_DISCERN: {
    id: 'CONFUSE_DISCERN',
    name: 'CONFUSE → DISCERN',
    chineseName: '困惑 → 明辨',
    archetype: '铁律聚焦型',
    summary: '多头绪的混乱让人无所适从，必须快刀斩乱麻，确立绝对的第一优先级。',
    coreAdvice: '砍掉所有次要枝节，只保最重要的那一根主线。',
    deepReflection: '哪一条核心原则能帮你一秒识破所有伪需求？',
    tags: ['聚焦', '主线', '断舍离'],
  },
  RESIST_RELEASE: {
    id: 'RESIST_RELEASE',
    name: 'RESIST → RELEASE',
    chineseName: '抗拒 → 归零',
    archetype: '彻底放下型',
    summary: '抗拒现实只会让痛苦倍增，彻底认输并放手，反而是赢得新生的唯一解。',
    coreAdvice: '允许失败与结束，彻底将过去归零。',
    deepReflection: '如果彻底认输不再背负，你的心神将多么自由？',
    tags: ['认输', '放手', '彻底解脱'],
  },
  OVERTHINK_SIMPLIFY: {
    id: 'OVERTHINK_SIMPLIFY',
    name: 'OVERTHINK → SIMPLIFY',
    chineseName: '内耗 → 极简',
    archetype: '大道至简型',
    summary: '把简单的问题想得无比复杂，答案往往就藏在最朴素直接的一步之中。',
    coreAdvice: '去掉所有花哨的推演，走最直接的那条路。',
    deepReflection: '这件事如果交给一个小孩来做，他会怎么选？',
    tags: ['极简', '朴素', '直接'],
  },
  DISCONNECT_RECONNECT: {
    id: 'DISCONNECT_RECONNECT',
    name: 'DISCONNECT → RECONNECT',
    chineseName: '疏离 → 共鸣',
    archetype: '重归连接型',
    summary: '冰冷的孤立筑起了高墙，唯有重新找回对人、对事的热爱与信任才能融化坚冰。',
    coreAdvice: '主动伸出信任的橄榄枝，建立温暖连接。',
    deepReflection: '放下防备去爱与相信，这本身就是最勇敢的英雄主义。',
    tags: ['连接', '信任', '共鸣'],
  },
}

// 64 Block-to-Key Matrix mapping [blockColor][keyColor]
export const BLOCK_TO_KEY_MAP: Record<ColorId, Record<ColorId, PatternArchetype>> = {
  white: {
    white: PATTERN_ARCHETYPES.RESIST_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.WAIT_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.END_BEGIN,
    yellow: PATTERN_ARCHETYPES.CONFUSE_DISCERN,
    orange: PATTERN_ARCHETYPES.CHASE_WAIT,
    red: PATTERN_ARCHETYPES.PAUSE_ACT,
  },
  purple: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.SENSE_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.FORCE_SHIFT,
    yellow: PATTERN_ARCHETYPES.CONFUSE_DISCERN,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.THINK_ACT,
  },
  blue: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.HIDE_EXPRESS,
    pink: PATTERN_ARCHETYPES.DISCONNECT_RECONNECT,
    green: PATTERN_ARCHETYPES.FORCE_SHIFT,
    yellow: PATTERN_ARCHETYPES.FEEL_CLARIFY,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.THINK_ACT,
  },
  pink: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.HIDE_EXPRESS,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.FORCE_SHIFT,
    yellow: PATTERN_ARCHETYPES.FEEL_CLARIFY,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.PLAN_MOVE,
  },
  green: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.WAIT_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.DOUBT_VERIFY,
    yellow: PATTERN_ARCHETYPES.CONFUSE_DISCERN,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.PLAN_MOVE,
  },
  yellow: {
    white: PATTERN_ARCHETYPES.OVERTHINK_SIMPLIFY,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.WAIT_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.DOUBT_VERIFY,
    yellow: PATTERN_ARCHETYPES.CONFUSE_DISCERN,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.THINK_ACT,
  },
  orange: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.WAIT_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.FORCE_SHIFT,
    yellow: PATTERN_ARCHETYPES.CONFUSE_DISCERN,
    orange: PATTERN_ARCHETYPES.CHASE_WAIT,
    red: PATTERN_ARCHETYPES.PAUSE_ACT,
  },
  red: {
    white: PATTERN_ARCHETYPES.HOLD_RELEASE,
    purple: PATTERN_ARCHETYPES.REACT_OBSERVE,
    blue: PATTERN_ARCHETYPES.WAIT_SPEAK,
    pink: PATTERN_ARCHETYPES.FEEL_ACCEPT,
    green: PATTERN_ARCHETYPES.FORCE_SHIFT,
    yellow: PATTERN_ARCHETYPES.FEEL_CLARIFY,
    orange: PATTERN_ARCHETYPES.PUSH_PAUSE,
    red: PATTERN_ARCHETYPES.PLAN_MOVE,
  },
}

export function getBlockToKeyPattern(blockColor: ColorId, keyColor: ColorId): PatternArchetype {
  return BLOCK_TO_KEY_MAP[blockColor]?.[keyColor] || PATTERN_ARCHETYPES.FORCE_SHIFT
}
